image: golang:latest

variables:
  BIN_NAME: lewdbot-discord
  ARTIFACTS_DIR: artifacts
  GO_PROJECT:  github.com/softashell/lewdbot-discord

before_script:
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - go get -d -v

build:linux64:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}

test:
  stage: test
  script:
    - go test -v ./...
