image: golang:latest

variables:
  BIN_NAME: lewdbot-discord
  ARTIFACTS_DIR: artifacts
  GO_PROJECT:  github.com/softashell/lewdbot-discord

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

build:linux64:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}

test:
  stage: test
  script:
    - go test -v ./...
