image: golang:latest

before_script:
  - go get -d -v
  - git -C "$GOPATH/src/github.com/bwmarrin/discordgo" checkout develop

build:linux64:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - go build

test:
  stage: test
  script:
    - go test
